name: Build and Release Executables

# [BEST PRACTICE] a concurrency group to ensure only one run per tag is active at a time.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build on ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # Using Python 3.10 for better compatibility, as your log showed an attempt with 3.12
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # Build with PyInstaller, forcing bash shell for cross-platform compatibility
      - name: Build with PyInstaller
        shell: bash
        run: |
          echo "Listing files in the current directory:"
          ls -l

          # Specify the main application script
          SCRIPT_NAME="encryptor_gui.py"

          # Use different parameters based on the operating system
          if [ "${{ runner.os }}" == "Windows" ]; then
            pyinstaller --name="CryptoApp_Win" --onefile --windowed --icon="icon.ico" $SCRIPT_NAME
          elif [ "${{ runner.os }}" == "macOS" ]; then
            pyinstaller --name="CryptoApp_macOS" --onefile --windowed --icon="icon.icns" $SCRIPT_NAME
          else # Linux
            pyinstaller --name="CryptoApp_Linux" --onefile --windowed $SCRIPT_NAME
          fi

      # Prepare artifacts for release by renaming them consistently
      - name: Prepare artifact for release
        shell: bash
        run: |
          cd dist
          if [ "${{ runner.os }}" == "Windows" ]; then
            mv CryptoApp_Win.exe ../CryptoApp-Windows-x86_64.exe
          elif [ "${{ runner.os }}" == "macOS" ]; then
            mv CryptoApp_macOS ../CryptoApp-macOS-x86_64
          else # Linux
            mv CryptoApp_Linux ../CryptoApp-Linux-x86_64
          fi
          cd ..
          echo "Final files prepared for release:"
          ls -l

      # Create a GitHub Release and upload the built executables as assets
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            CryptoApp-Windows-x86_64.exe
            CryptoApp-macOS-x86_64
            CryptoApp-Linux-x86_64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

